url: https://www.dhinstitutes.org
# this should also be secured in the .htaccess file

sass:
    load_paths:
        - _sass
        - node_modules
        - assets/_sass
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - Makefile
  - README.md

dirs:
  icons: /assets/icons/
