url: "http://www.dhinstitutes.org"
dirs:
  img: "/assets/images/"
  icon: "/assets/images/icons/"
  css: "/assets/css/"
  js: "/assets/js/"
  logo: "/assets/images/logos/"

main-menu:
    - ["/pages/about.html", "About"]
    - ["/pages/people.html", "People"]
    - ["/pages/curriculum.html", "Curriculum"]
    - ["/pages/network.html", "Network"]
    - ["/pages/dhri_gc.html", "DHRI@GC"]
    - ["/pages/partners.html", "Partners"]
    - ["/pages/reports.html", "Reports"]


sass:
  sass_dir: _assets/_sass
  # style: compressed

plugins:
  - jekyll-sitemap

collections:
  assets:
    output: true

exclude: ['README.md', "Gemfile", "Gemfile.lock"]